SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV

## GROUP BY를 사용하면 각 연도별로 최댓값인 행 하나씩만 남으므로 계산 불가, 따라서 서브쿼리 혹은 윈도우함수를 사용해야함
